services:
  mongodb:
    image: mongo:8.2.3
    container_name: ${PACKAGE_NAME}_mongodb
    restart: always
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - network
    profiles:
      - infra
      - dev
      - prod

  rabbitmq:
    image: rabbitmq:4.2.2-management
    container_name: ${PACKAGE_NAME}_rabbitmq
    restart: always
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - network
    profiles:
      - infra
      - dev
      - prod

  redis-master:
    image: redis:7.2.6-alpine
    container_name: ${PACKAGE_NAME}_redis-master
    restart: always
    command:
      [
        'redis-server',
        '--appendonly',
        'yes',
        '--bind',
        '0.0.0.0',
        '--protected-mode',
        'no',
      ]
    ports:
      - '22376:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - network
    profiles:
      - infra
      - dev
      - prod

  redis-replica:
    image: redis:7.2.6-alpine
    container_name: ${PACKAGE_NAME}_redis-replica
    restart: always
    command:
      [
        'redis-server',
        '--replicaof',
        'redis-master',
        '6379',
        '--bind',
        '0.0.0.0',
        '--protected-mode',
        'no',
      ]
    ports:
      - '22377:6379'
    depends_on:
      - redis-master
    networks:
      - network
    profiles:
      - prod

  mongo-express:
    image: mongo-express:1.0.2
    container_name: ${PACKAGE_NAME}_mongo_express
    restart: always
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - network
    profiles:
      - infra
      - prod
      - dev

volumes:
  mongodb_data:
  rabbitmq_data:
  redis_data:

networks:
  network:
    name: ${PACKAGE_NAME}-network
    driver: bridge
