services:
  mongodb:
    image: mongo:8.2.3
    container_name: vortex_mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - vortex-network

  rabbitmq:
    image: rabbitmq:4.2.2-management
    container_name: vortex_rabbitmq
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - vortex-network

  redis:
    image: redis:7.2-alpine
    container_name: vortex_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - vortex-network

  # Development Tools
  mongo-express:
    image: mongo-express:latest
    container_name: vortex_mongo_express
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - vortex-network
    profiles:
      - tools

volumes:
  mongodb_data:
  rabbitmq_data:
  redis_data:

networks:
  vortex-network:
    driver: bridge
