export enum ServicePort {
  GATEWAY = 3000,
  AUTH = 3001,
  PRODUCT = 3002,
  ORDER = 3003,
  NOTIFICATION = 3004,
}

export enum EventName {
  ORDER_CREATED = 'order.created',
  PRODUCT_CREATED = 'product.created',
  PRODUCT_UPDATED = 'product.updated',
}

export enum QueueName {
  NOTIFICATION_QUEUE = 'notification_queue',
  ORDER_QUEUE = 'order_queue',
}

export enum ENVEnum {
  NODE_ENV = 'NODE_ENV',
  MONGODB_URI = 'MONGODB_URI',
  PORT = 'PORT',
  RABBITMQ_URL = 'RABBITMQ_URL',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',

  BASE_URL = 'BASE_URL',
  FRONTEND_BASE = 'FRONTEND_BASE',

  MAIL_USER = 'MAIL_USER',
  MAIL_PASS = 'MAIL_PASS',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_USERNAME = 'REDIS_USERNAME',
  REDIS_PASSWORD = 'REDIS_PASSWORD',

  SUPER_ADMIN_EMAIL = 'SUPER_ADMIN_EMAIL',
  SUPER_ADMIN_PASS = 'SUPER_ADMIN_PASS',

  STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY',
  STRIPE_WEBHOOK_SECRET = 'STRIPE_WEBHOOK_SECRET',

  FIREBASE_PROJECT_ID = 'FIREBASE_PROJECT_ID',
  FIREBASE_CLIENT_EMAIL = 'FIREBASE_CLIENT_EMAIL',
  FIREBASE_PRIVATE_KEY = 'FIREBASE_PRIVATE_KEY',

  AWS_REGION = 'AWS_REGION',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  AWS_S3_BUCKET_NAME = 'AWS_S3_BUCKET_NAME',
}
