export enum AuthEnv {
  MONGODB_URI = 'MONGODB_URI',
  JWT_SECRET = 'JWT_SECRET',
  PORT = 'PORT',
  RABBITMQ_URL = 'RABBITMQ_URL',
  SUPERADMIN_EMAIL = 'SUPERADMIN_EMAIL',
  SUPERADMIN_PASSWORD = 'SUPERADMIN_PASSWORD',
  APP_URL = 'APP_URL',
}
