export enum GatewayEnv {
  PORT = 'PORT',
  AUTH_SERVICE_URL = 'AUTH_SERVICE_URL',
  PRODUCT_SERVICE_URL = 'PRODUCT_SERVICE_URL',
  ORDER_SERVICE_URL = 'ORDER_SERVICE_URL',
  NOTIFICATION_SERVICE_URL = 'NOTIFICATION_SERVICE_URL',
}
