export enum PaymentEnv {
  PORT = 'PORT',
  STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY',
  STRIPE_WEBHOOK_SECRET = 'STRIPE_WEBHOOK_SECRET',
  ORDER_SERVICE_URL = 'ORDER_SERVICE_URL',
  PRODUCT_SERVICE_URL = 'PRODUCT_SERVICE_URL',
  JWT_SECRET = 'JWT_SECRET',
  INTERNAL_SECRET = 'INTERNAL_SECRET',
}
